#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void initialize();			//inisiasi setting motor & sensor
void DFSAction();
bool inColor();					//Ngecek posisi di blok warna
bool inLine();          //Ngecek di garis atau kaga
void followLine();			//Ngikutin garis doang
void moveForward();     //maju lurus doang
void turnRight();
void turnLeft();
void brake();

task main()
{
	initialize();
	//while(1)
		followLine();
}

void initialize()
{
	setMotorBrakeMode(leftMotor,motorBrake);
	setMotorBrakeMode(rightMotor,motorBrake);
}

void DFSAction()
{

}

bool inColor()
{
	return (getColorName(colorSensor)==colorRed || getColorName(colorSensor)==colorBlue || getColorName(colorSensor)==colorGreen || getColorName(colorSensor)==colorYellow);
}

bool inLine()
{
	return (inColor() || getColorName(colorSensor)==colorBlack);
}

void followLine()
{
	bool switcher = false;             //turn slightly right if 1
	while (!inColor())
	{
		while (inLine())
			moveForward();
		if (!inLine() && !inColor())
		{
			brake();
			if (switcher)
			{
				while (!inLine())
				{
					turnRight();
				}
			}
			else
			{
				while (!inLine())
				{
					turnLeft();
				}
			}
			switcher = !switcher;
		}
	}
}

void moveForward()
{
	setMotorSync(leftMotor,rightMotor,0,100);
	setMotorSpeed(leftMotor,100);
	delay(2);
	brake();
}

void turnRight()
{
	setMotorSpeed(rightMotor,100);
	setMotorSpeed(leftMotor,-100);
	delay(2);
	brake();
}

void turnLeft()
{
	setMotorSpeed(rightMotor,-100);
	setMotorSpeed(leftMotor,100);
	delay(2);
	brake();
}

void brake()
{
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,0);
}
