#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void initialize();			//inisiasi setting motor & sensor
void BFSAction();
bool inColor();					//Ngecek posisi di blok warna
bool inLine();          //Ngecek di garis atau kaga
void followLine();			//Ngikutin garis doang
void moveForward();     //maju lurus doang
void turnRight();  			//belok kanan 90"
void turnLeft();				//belok kiri 90"
void brake();

task main()
{
	initialize();
	moveForward();
	delay(500);
	brake();
}

void initialize()
{
	setMotorBrakeMode(leftMotor,motorBrake);
	setMotorBrakeMode(rightMotor,motorBrake);
}
void moveForward()
{
	setMotorSync(leftMotor,rightMotor,0,100);
	setMotorSpeed(leftMotor,100);
}

void brake()
{
	setMotorSpeed(leftMotor,0);
	setMotorSpeed(rightMotor,0);
}
